### ISSUE TITLE
Coletor para o Template1 (22) - Licitações

### ISSUE THREAD

**Issue by CinthiaS** [MPMG-DCC-UFMG/F01#185]
- [x] Conceição das Alagoas - 388
- [x] Nova Ponte - 178
- [x] Iturama - 112
- [x] Pedrinópolis - 425
- [x] Perdizes - 713
- [x] Patos de Minas - 626
- [x] Indianópolis - 402
- [x] Araxá - 623
- [x] Carmo do Paranaíba - 387
- [x] Rio Paranaíba - 9
- [x] Cascalho Rico - 342
- [x] São Gotardo - 156
- [x] Tupaciguara -  211
- [x] Veríssimo - 746
- [x] Tiros - 489
- [x] Centralina - 184
- [x] Pratinha - 532
- [x] Cruzeiro da Fortaleza - 435
- [x] Campo Florido - 187
- [x] Estrela do Sul - 253
- [x] Água Comprida - 21
- [x] Serra do Salitre - 790 (Fora do ar)
