### ISSUE TITLE
Coletor para o template ADPM (22) - Licitações

### ISSUE THREAD

**Issue by CinthiaS** [MPMG-DCC-UFMG/F01#186]
- [x] Buritis
- [x] Arinos
- [x] Nova União
- [x] Marmelópolis
- [x] São João da Mata
- [x] Piranguinho
- [x] São Pedro do Suaçuí
- [x] Bom Jesus do Amparo
- [x] Cedro do Abaeté
- [x] Serro
- [x] Pedralva
- [x] Paineiras
- [x] Silvianópolis
- [x] Brazópolis
- [x] Taquaraçu de Minas
- [x] Abaeté
- [x] Biquinhas
- [x] Dom Silvério
- [x] Wenceslau Braz
- [x] Piranguçu
- [x] Consolação
- [x] Itapecerica
