### ISSUE TITLE
Coletor para o template Síntese Tecnologia e Informática - Despesas - Contas Públicas

### ISSUE THREAD

**Issue by CinthiaS** [MPMG-DCC-UFMG/F01#190]
DoD: Coletor para o template Síntese Tecnologia e Informática para a tag Despesas e teste de generalização para os municípios.

- [x] Ibiaí 
- [x] Presidente Kubitschek
- [ ] Turmalina
- [ ] Engenheiro Navarro
- [ ] Chapada Gaúcha
- [ ] Francisco Badaró
- [ ] Frei Lagonegro
- [ ] Gameleiras
- [ ] Alvorada de Minas
- [ ] Claro dos Poções
- [ ] Água Boa
- [ ] Novorizonte
- [ ] Cachoeira de Pajeú
- [ ] Berilo
- [ ] Patis
- [ ] Espinosa
- [ ] Bonito de Minas
- [ ] São João da Lagoa
- [ ] Materlândia
- [ ] Gouveia
- [ ] Ponto Chique
- [ ] Catuti
- [ ] Fruta de Leite
- [ ] Mirabela
- [ ] Itinga
- [ ] Felício dos Santos
- [ ] Senador Modestino Gonçalves
- [ ] Itamarandiba 
- [ ] Coração de Jesus
- [ ] Francisco Sá
- [ ] Josenópolis
- [ ] São Romão
- [ ] Indaiabira
- [ ] Pintópolis
- [ ] Mamonas
- [ ] Datas
- [ ] Jaíba
- [ ] Augusto de Lima
- [ ] Juramento
- [ ] Capitão Enéas
- [ ] Janaúba
- [ ] Cristália
- [ ] Guaraciama
- [ ] Pai Pedro
- [ ] Águas Vermelhas
- [ ] Bocaiúva
- [ ] Várzea da Palma
- [ ] Divisópolis
- [ ] Virgem da Lapa
- [ ] Novo Cruzeiro
- [ ] Glaucilândia
- [ ] Divisa Alegre
- [ ] São Gonçalo do Rio Preto
- [ ] Capelinha
- [ ] Lontra
- [ ] Curral de Dentro
- [ ] São João das Missões
- [ ] Jequitaí
- [ ] Rio Pardo de Minas
- [ ] Nova Porteirinha
- [ ] Aricanduva
- [ ] Ladainha
- [ ] Serra Azul de Minas
- [ ] Coluna
- [ ] Mário Campos
- [ ] Vargem Grande do Rio Pardo
- [ ] Joaquim Felício
- [ ] Monte Azul
- [ ] Miravânia
- [ ] Couto de Magalhães de Minas
- [ ] Mato Verde
- [ ] Pedra Azul
- [ ] Santa Cruz de Salinas
- [ ] Brasília de Minas
- [ ] Mata Verde
- [ ] Itacambira
- [ ] Santo Hipólito
- [ ] Padre Carvalho
- [ ] Santana do Riacho
- [ ] Jenipapo de Minas
- [ ] Veredinha
- [ ] Santo Antônio do Retiro
- [ ] São João do Pacuí
- [ ] Manga
- [ ] Montezuma
- [ ] Itacarambi
