### ISSUE TITLE
Adequar os validadores  a nova checklist -  (Concursos Públicos)

### ISSUE THREAD

**Issue by CinthiaS** [MPMG-DCC-UFMG/F01#40]
Dod: Refatorar os validadores da Tag Concursos Públicos  para a nova checklist já adicionando a a integração com o indexador.

- Dados do Concurso 
- [ ]  Status do andamento do processo do concurso
- [ ]  Resultado
- [ ]  Atos de nomeação

- [ ]  Cópia do edital do concurso
- [ ]  Divulgação dos recursos e respectivas decisões
