### ISSUE TITLE
Adequar os validadores a nova checklist - (Despesas/Relatórios)

### ISSUE THREAD

**Issue by CinthiaS** [MPMG-DCC-UFMG/F01#55]
Dod: Refatorar os validadores da Tag Despesas/Relatórios para a nova checklist já adicionando a a integração com o indexador.

Validadores para subtag relatórios:

- [x]  Link de acesso ao Plano Plurianual do município
- [x]  Link de acesso à Lei de Diretrizes Orçamentaria do município
- [x]  Link de acesso à Lei Orçamentária Anual do município
- [x]  Apresentação do balanço anual, com as respectivas demonstrações contábeis
- [x]  Relatórios da execução orçamentária e gestão fiscal
