### ISSUE TITLE
Coletor para o template da Betha (37) (Licitações)

### ISSUE THREAD

**Issue by CinthiaS** [MPMG-DCC-UFMG/F01#81]
DoD: Coletor para o template Betha (7) para a tag Licitações e teste de generalização para os municípios.

- [x] Alfenas
- [x] Alterosa
- [x] Alto Rio Doce
- [x] Alvinópolis
- [x] Bandeira do Sul
- [x] Boa Esperança
- [x] Botelhos
- [x] Cambuquira
- [x] Campos Gerais
- [x] Cataguases
- [x] Cláudio
- [x] Coinceição da Aparecida
- [x] Congonhas
- [x] Formiga
- [x] Guaranésia
- [x] Igaratinga
- [x] Ijaci
- [x] Itapeva
- [x] Itatiaiuçu
- [x] Lagoa da Prata
- [x] Luz
- [x] Mantena
- [x] Mariana
- [x] Nepomuceno
- [x] Ouro Branco
- [x] Pequi
- [x] Pirajuba
- [x] Planura
- [x] Raposos
- [x] Rio Casca
- [x] Rio Doce
- [x] Sacramento
- [x] Santo Antônio do Monte
- [x] São Sebastião do Oeste
- [x] Sarzedo
- [x] Serrania
