### ISSUE TITLE
Coletor para o template Síntese Tecnologia e Informática -Licitações

### ISSUE THREAD

**Issue by CinthiaS** [MPMG-DCC-UFMG/F01#90]
DoD: Coletor para o template Síntese Tecnologia e Informática para a tag Licitações e teste de generalização para os municípios.

- [x] Ibiaí
- [x] Presidente Kubitschek
- [x] Turmalina
- [x] Engenheiro Navarro
- [x] Chapada Gaúcha
- [x] Francisco Badaró
- [x] Frei Lagonegro
- [x] Gameleiras
- [x] Alvorada de Minas
- [x] Claro dos Poções
- [x] Água Boa
- [x] Novorizonte
- [x] Cachoeira de Pajeú
- [x] Berilo
- [x] Patis
- [x] Setubinha
- [x] Espinosa
- [x] Bonito de Minas
- [x] São João da Lagoa
- [x] Materlândia
- [x] Gouveia
- [x] Ponto Chique
- [x] Catuti
- [x] Fruta de Leite
- [x] Mirabela
- [x] Itinga
- [x] Felício dos Santos
- [x] Senador Modestino Gonçalves
- [x] Itamarandiba
- [x] Dores de Guanhães
- [x] Coração de Jesus
- [x] Francisco Sá
- [x] Josenópolis
- [x] São Romão
- [x] Indaiabira
- [x] Pintópolis
- [x] Mamonas
- [x] Datas
- [x] Jaíba
- [x] Augusto de Lima
- [x] Juramento
- [x] Capitão Enéas
- [x] Janaúba
- [x] Cristália
- [x] Guaraciama
- [x] Pai Pedro
- [x] Águas Vermelhas
- [x] Bocaiúva
- [x] Várzea da Palma
- [x] Divisópolis
- [x] Virgem da Lapa
- [x] Novo Cruzeiro
- [x] Glaucilândia
- [x] Divisa Alegre
- [x] São Gonçalo do Rio Preto
- [x] Capelinha
- [x] Lontra
- [x] Curral de Dentro
- [x] São João das Missões
- [x] Jequitaí
- [x] Rio Pardo de Minas
- [x] Nova Porteirinha
- [x] Aricanduva
- [x] Ladainha
- [x] Serra Azul de Minas
- [x] Coluna
- [x] Mário Campos
- [x] Vargem Grande do Rio Pardo
- [x] Joaquim Felício
- [x] Monte Azul
- [x] Miravânia
- [x] Couto de Magalhães de Minas
- [x] Mato Verde
- [x] Pedra Azul
- [x] Santa Cruz de Salinas
- [x] Brasília de Minas
- [x] Mata Verde
- [x] Itacambira
- [x] Santo Hipólito
- [x] Padre Carvalho
- [x] Santana do Riacho
- [x] Jenipapo de Minas
- [x] Veredinha
- [x] Santo Antônio do Retiro
- [x] São João do Pacuí
- [x] Manga
- [x] Montezuma
- [x] Itacarambi
