### ISSUE TITLE
Coletor para o template da PT (45) (Licitações)

### ISSUE THREAD

**Issue by CinthiaS** [MPMG-DCC-UFMG/F01#96]
DoD: Coletor para o template PT (45) para a tag Licitações e teste de generalização para os municípios.
- [x] Barroso - 221
- [x] Casa Grande - 699
- [x] Luminárias - 220
- [x] Douradoquara - 474 (outro template HD)
- [x] Catas Altas da Noruega - 792
- [x] Dores de Campos - 813
- [x] Careaçu - 323
- [x] São Brás do Suaçuí - 674
- [x] Nazareno - 530
- [x] Entre Rios de Minas - 784
- [x] Santana dos Montes - 46
- [x] Conceição da Barra de Minas - 689
- [x] Coronel Xavier Chaves - 671
- [x] Carandaí - 471
- [x] Santa Bárbara do Tugúrio - 533
- [x] São Vicente de Minas - 329
- [ ] Conceição da Aparecida - 550 (outro template betha)
- [x] Ressaquinha - 393
- [x] Itumirim - 282
- [x] Tiradentes - 752
- [x] Visconde do Rio Branco - 217
- [x] Itutinga - 461
- [x] Carrancas - 487
- [x] Rio Acima - 328
- [x] Jeceaba - 804
- [x] Descoberto - 596
- [x] Queluzito - 413
- [x] Ibituruna - 244
- [x] Santa Cruz de Minas - 268
- [x] São João del Rei - 352
- [x] Prados - 833
- [x] Antônio Carlos - 761
- [x] Alfredo Vasconcelos - 371
- [x] Ingaí - 565
- [x] São Tiago - 346
- [x] Belo Vale - 480
- [x] Santana do Jacaré - 806
- [x] São Geraldo - 756
- [x] Silveirânia - 248
- [x] Ritápolis - 56
- [x] Resende Costa - 774
- [x] Ervália- 143
- [x] Conceição dos Ouros - 622
- [x] Lagoa Dourada - 796
- [x] Piedade do Rio Grande - 441
